minecraft:
  serverIP: play.pika-network.net
  serverPort: 25565
  joinCommand: /server factions
  version: 1.19.2

discord: # Webhook links, tutorial: https://www.youtube.com/watch?v=fKksxz2Gdnc&ab_channel=NoIntroTutorials
  botLogs:
  serverChat:
  commandLogs:
  vanishedLogs:
  ftop:
  flist:

  webhookUrl: https://discord.com/api/webhooks/1232532210867769374/JBpDQsqqL89WugmHE8CqSbISMrh7LwUZGF06TLpxLq5twChhXcjoB6uJ9UnXvV1nQx8Y # Avatar of your Webhook
  webhookColor: 8f04d4 # Needs to be a HEX color code without the "#" 


settings:
  prefix: "!"
  ftopCommand: "/f top" # Change this to the command that shows FTOP in chat
  vanishCheck: true # Enable vanish check?
  useChat: true # Allow the bot to use chat

layouts:   # Pika-Network version (Don't change flist, no need for FTOP)
  flist: "     * &Faction& (&Online&/&Max&) »    &Claims&"

times: # Number in minutes
  ftop: 5
  flist: 30
  vanishCheck: 1

whitelist: # CaSe SeNsItIvE
  - GetDutched
  - BigGamer420
